# Assignment 1 – Log File Analyzer

## Problem Statement

Parse application log files to identify ERROR and WARNING entries, group them by module, and produce a CSV report showing error frequency.

In [4]:
#import the required libs

import pandas as pd

In [6]:
#parsing the log file to split them to parts and convert to Dataframe
log_data=[]

with open("application.log",'r') as file:
  for line in file:
    line = line.strip()
    parts = line.split(" ",4)
    log_data.append(parts)

print("Total log entries:",len(log_data))

Total log entries: 200

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
#create dataframe from the log data
df = pd.DataFrame(
    log_data,
    columns=["Date","Time","Log Level","Module","Message"]
)

df.head()

         Date      Time Log Level              Module                  Message
0  2026-07-16  09:01:26      INFO     InventoryModule  Email sent successfully
1  2026-07-16  09:01:59      INFO      DatabaseModule     User profile updated
2  2026-07-16  09:02:15      INFO         LoginModule    User login successful
3  2026-07-16  09:02:31      INFO         LoginModule     User profile updated
4  2026-07-16  09:03:01   WARNING  NotificationModule        High memory usage

In [8]:
#check valueable info to see what the datatypes are for each column and see if there are any missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       200 non-null    object
 1   Time       200 non-null    object
 2   Log Level  200 non-null    object
 3   Module     200 non-null    object
 4   Message    200 non-null    object
dtypes: object(5)
memory usage: 7.9+ KB

In [9]:
#we see that there are no missing values here and verifiy it using this command
df.isnull().sum()

Date         0
Time         0
Log Level    0
Module       0
Message      0
dtype: int64

In [24]:
#Filter ERROR and WARNIGN entries

filtered_log = df[df["Log Level"].isin(["ERROR","WARNING"])]
print(filtered_log.shape) #to see the number of rows in both level
filtered_log.head()

(75, 5)

,Date,Time,Log Level,Module,Message
4,2026-07-16,09:03:01,WARNING,NotificationModule,High memory usage
12,2026-07-16,09:10:44,WARNING,LoginModule,High memory usage
15,2026-07-16,09:15:48,ERROR,PaymentModule,Inventory synchronization failed
17,2026-07-16,09:18:00,WARNING,EmailModule,Multiple failed login attempts
19,2026-07-16,09:20:56,WARNING,LoginModule,High memory usage

In [21]:
#filtering the count based on modules for ERROR and WARNING

filtered_log.groupby("Module").size()

Module
AuthModule            10
DatabaseModule         9
EmailModule           11
InventoryModule       11
LoginModule            9
NotificationModule     9
OrderModule            6
PaymentModule         10
dtype: int64

In [26]:
error_report = (
    filtered_log
        .groupby("Module")
        .size()
        .reset_index(name="Error/Warning Count")
        .sort_values(by="Error/Warning Count", ascending=False)
)

error_report

               Module  Error/Warning Count
3     InventoryModule                   11
2         EmailModule                   11
0          AuthModule                   10
7       PaymentModule                   10
1      DatabaseModule                    9
4         LoginModule                    9
5  NotificationModule                    9
6         OrderModule                    6

In [30]:
total_issues = error_report["Error/Warning Count"].sum()

error_report["Percentage"] = (
    error_report["Error/Warning Count"] / total_issues * 100
).round(2)

error_report

               Module  Error/Warning Count  Percentage
3     InventoryModule                   11       14.67
2         EmailModule                   11       14.67
0          AuthModule                   10       13.33
7       PaymentModule                   10       13.33
1      DatabaseModule                    9       12.00
4         LoginModule                    9       12.00
5  NotificationModule                    9       12.00
6         OrderModule                    6        8.00

In [31]:
#save the report as csv

error_report.to_csv('error_report.csv',index=False)
print("CSV report generated successfully!!")

CSV report generated successfully!!

## Observations

- A total of 200 application log entries were generated and analyzed.
- The log file contained four log levels: INFO, WARNING, ERROR, and DEBUG.
- Only ERROR and WARNING log entries were selected for analysis.
- The filtered log entries were grouped by module to determine the frequency of issues.
- The generated CSV report summarizes the number of ERROR and WARNING entries for each application module.
- This analysis helps identify modules that may require further debugging and performance improvements.